### PR TITLE
release: bumped to 0.13.0

### PR DESCRIPTION
**Pull request by parkhomenko**
### Notes
Bumped to 0.13.0 version

### CODE REVIEW

**Review by macnealefauna — DISMISSED** [review]
Ship It!

**Review by faunaee — CHANGES_REQUESTED** [review]
This PR, as is, is fine.

However, the README file does not contain an entry for the new `import` command. That seems necessary to include in the release.

**Comment by nishmad** [comment]
+1 on Ewan's comment. Once we have the new readme, let's make this available in npm

**Review by nishmad — APPROVED** [review]
Lgtm

**Review by faunaee — APPROVED** [review]
LGTM! 👍

**Pull request merged**
