### PR TITLE
chore(release): bump to 0.12.4

### PR DESCRIPTION
**Pull request by parkhomenko**
### Notes
Bumped to a version 0.12.4

### CODE REVIEW

**Comment by parkhomenko** [comment]
@faunaee There is no changelog in this repo, can we go without it? It would be tough to create it from scratch now. What do you think about it?

**Comment by faunaee** [comment]
We're still in the 0.x series of releases for this product, so I think we can do without release notes for now. We should make it a goal to add release notes for a future release.

Other than the changes in the PR, what else is included in 0.12.4?

**Comment by parkhomenko** [comment]
Here are the changes:
- shows error if user's secret is invalid
- fixed shell error (https://faunadb.atlassian.net/browse/OSS-464)
- fixed linter errors

**Review by faunaee — APPROVED** [review]
LGTM 👍

**Pull request merged**
