### PR TITLE
Changed single to double quotes. Added a few more.

### PR DESCRIPTION
**Pull request by danieltodonnell**
Running the mocha tests failed, but they seem unrelated to my changes, so I think some tests are failing naturally.  Can someone confirm?

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
The changes in the quotes look good for me.

**Comment by BrunoQuaresma** [comment]
The same here. I think we should have a "Running tests" section in the README.

**Comment by alvarofauna** [comment]
I think there are failing tests, see: https://github.com/fauna/fauna-shell/blob/master/docs/dev.md#running-tests

**Comment by alvarofauna** [comment]
@BrunoQuaresma @danieltodonnell do you plan on working on this PR?

**Comment by fauna-ryanharris** [comment]
@danieltodonnell @fauna-rodrigo I think we can close this PR in favor of Rodrigo's already-merged #32

**Comment by BrunoQuaresma** [comment]
@fauna-ryanharris makes sense. Feel free to close!

**Pull request closed without merging**
