### PR TITLE
Update faunadb-js dependency to 4.5.2 and node-fetch to 2.6.7

### PR DESCRIPTION
**Pull request by adambollen**
This PR contains some dependency and security fixes from npm:
* Update the dependency on the Fauna JS driver to 4.5.2 (released 2/4/22)
* Update the node-fetch version to 2.6.7
* `npm audit fix`
* Bump shell version to `0.14.0`

### CODE REVIEW

**Review by faunaee — DISMISSED** [review]
LGTM! 👍

**Review by faunaee — DISMISSED** [review]
LGTM! 👍

**Comment by adambollen** [comment]
FYI, here's the CircleCI run for the latest change: https://app.circleci.com/pipelines/github/fauna/fauna-shell/173/workflows/abf368c3-d149-4ffa-8f61-103ebbe6cffd/jobs/190

**Comment by faunaee** [comment]
Hmm... there's a Dependabot PR (#150 ) that updates node-fetch to 3.1.1. Can we include that here?

**Comment by adambollen** [comment]
> Hmm... there's a Dependabot PR (#150 ) that updates node-fetch to 3.1.1. Can we include that here?

I tried that first (still in my commit history), but it's a breaking change and the shell wouldn't start.  According to Lacework, 2.6.7 is the right target version.

**Review by faunaee — APPROVED** [review]
LGTM! 👍

**Review by cleve-fauna — APPROVED** [review]

**Pull request merged**
